# Generated by Django 4.2.3 on 2023-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('action', models.CharField(max_length=200)),
                ('pleasant_habit', models.BooleanField(default=False)),
                ('periodicity', models.PositiveIntegerField(default=1)),
                ('reward', models.CharField(max_length=200)),
                ('time_to_complete', models.DurationField()),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
