# Generated by Django 4.2.3 on 2023-08-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_habit_action_alter_habit_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='вознаграждение'),
        ),
    ]
