# Generated by Django 4.2.3 on 2023-08-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_habit_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, limit_choices_to={'reward__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.habit', verbose_name='связанная привычка'),
        ),
    ]
