# Generated by Django 4.2.3 on 2023-08-04 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_habit_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='send_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='время отправки уведомления'),
        ),
    ]
